name: Devpass checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        run: sudo apt-get install golang

      - name: Download test file
        run: curl -0 https://devpass-api-bucket.s3.amazonaws.com/testes/devpass-community/challenge-1700774255925/main_test.go -o main_test.go

      - name: Run unit tests
        run: go test
